### ISSUE TITLE
I can't deobfuscate this file

### ISSUE THREAD

**Issue by TTMTT** [0x1Avram/js-deobfuscator#10]
Hi @0x1Avram 
i tried your tool and i loved it .. thank you so much
can you see this file .. i think it's not fully deobfuscate:
https://pastebin.com/W3jcffpb

**Comment by 0x1Avram** [comment]
Hi @TTMTT !
Thank you for the feedback and the sample.

You are right, the sample was not deobfuscated correctly. I found a few bugs, fixed them and created a new release - [1.0.4](https://github.com/0x1Avram/js-deobfuscator/releases/tag/1.0.4) . I tested it on the file you provided and it seems to be deobfuscated properly with this new release. Please test it yourself and let me know if you encounter any other issues.
