### ISSUE TITLE
babel

### ISSUE THREAD

**Issue by Ashabbbb** [0x1Avram/js-deobfuscator#20]
[BABEL] Note: The code generator has deoptimised the styling of /home/thisismualtemailcuzzzz/js-deobfuscator/obfuscated.txt as it exceeds the max of 500KB.

**Comment by Ashabbbb** [comment]
how do i do more than 500KB?

**Comment by 0x1Avram** [comment]
I don’t know of any such limitations. I was able to transpile a file a few megabytes in size in the issue here -  https://github.com/0x1Avram/js-deobfuscator/issues/18 . From what I’ve read, it has to do with the babel configuration. If you can share the sample here or send it via email, I can look into it.

**Comment by Ashabbbb** [comment]
How can i do that?

**Comment by 0x1Avram** [comment]
Add it to pastebin or some other file sharing site and share the link. Or you can find my e-mail in the comments from here - https://github.com/0x1Avram/js-deobfuscator/issues/8 .

**Comment by Ashabbbb** [comment]
no i understand i dont understand what do i need to hand to you

**Comment by Ashabbbb** [comment]
if its possible can we talk in discord or telegram?

**Comment by 0x1Avram** [comment]
I would need the obfuscated code that produces the error you mentioned. 
I don't have any (discord, telegram). You can reach me via email.

**Comment by Ashabbbb** [comment]
[CrystalD.txt](https://github.com/0x1Avram/js-deobfuscator/files/11251462/CrystalD.txt)
[CrystalO.txt](https://github.com/0x1Avram/js-deobfuscator/files/11251464/CrystalO.txt)

**Comment by Ashabbbb** [comment]
sent them via gtihub

**Comment by 0x1Avram** [comment]
You need to set the compact option to false in the .babelrc file. I updated the docs. 
Regarding the actual deobfuscation, this won't work as this file seems to have each method obfuscated separately which is something I haven't seen in the obfuscator source code so the deobfuscator does not support it.

**Comment by Ashabbbb** [comment]
![image](https://user-images.githubusercontent.com/130922967/232853804-6544b1bd-274e-48af-8d9a-db84c07f5231.png)

**Comment by Ashabbbb** [comment]
this is what i get

**Comment by Ashabbbb** [comment]
the file name should be babelrc.babelrc ?

**Comment by Ashabbbb** [comment]
If possible can you record a video?

**Comment by 0x1Avram** [comment]
The name of the configuration file should be exactly ".babelrc" (without the quotes).

**Comment by Ashabbbb** [comment]
Ohhh thanks ye now it works
