### ISSUE TITLE
Error when transforming the input source code to AST

### ISSUE THREAD

**Issue by 3052** [0x1Avram/js-deobfuscator#21]
error: [deobfuscator.js] Error when transforming the input source code to AST. This is an 'esprima' parser limitation and the code needs to be transpiled to an esprima compatible version before passing it to the deobfuscator. error = Error: Line 1: Unexpected token .... Stack = Error: Line 1: Unexpected token ...

https://github.com/0x1Avram/js-deobfuscator/files/13258628/obf.txt

**Comment by 0x1Avram** [comment]
You need to transpile the file to a version that esprima can parse. There are instructions on how to do that in the readme of this project under the ‘Notes’ subsection.
