### ISSUE TITLE
Not finish stage 

### ISSUE THREAD

**Issue by tecnoweb** [0x1Avram/js-deobfuscator#8]
Version 1.0

info: [index.js] Starting deobfuscation process. {"timestamp":"16:58:43"}
info: [deobfuscator.js] Generating AST from obfuscated source code. {"timestamp":"16:58:43"}
info: [deobfuscator.js] Deobfuscating AST. {"timestamp":"16:58:44"}
info: [deobfuscator.js] 1/12) Deobfuscating stage 'StringArray'. {"timestamp":"16:58:44"}
info: [stage_deobfuscator.js] 1/1) Transform 'StringArraySyntheticTransformer'. {"timestamp":"16:58:45"}
info: [stage_03_stringarray.js] stringArrayTemplateFunctionName = e. {"timestamp":"16:58:45"}
info: [stage_03_stringarray.js] stringArrayCallsWrapperTemplateFunctionName = f. {"timestamp":"16:58:46"}
info: [stage_03_stringarray.js] Found nodeWithStringArrayRotateFunction. {"timestamp":"16:58:46"}

Version 1.2
info: [index.js] Starting deobfuscation process. {"timestamp":"17:01:18"}
info: [deobfuscator.js] Generating AST from obfuscated source code. {"timestamp":"17:01:18"}
info: [deobfuscator.js] Deobfuscating AST. {"timestamp":"17:01:18"}
info: [deobfuscator.js] 1/12) Deobfuscating stage 'StringArray'. {"timestamp":"17:01:18"}
info: [stage_deobfuscator.js] 1/1) Transform 'StringArraySyntheticTransformer'. {"timestamp":"17:01:18"}
info: [stage_03_stringarray.js] stringArrayTemplateFunctionName = M. {"timestamp":"17:01:18"}
info: [stage_03_stringarray.js] stringArrayCallsWrapperTemplateFunctionName = K. {"timestamp":"17:01:18"}
info: [stage_03_stringarray.js] Found nodeWithStringArrayRotateFunction. {"timestamp":"17:01:19"}
info: Addding found stringarray template to execution context. {"timestamp":"17:01:19"}
info: Addding found stringarray calls wrappers templates to execution context. {"timestamp":"17:01:19"}
info: Addding found stringarray rotate template to execution context. {"timestamp":"17:01:19"}
info: Finished adding stringarray specific nodes. {"timestamp":"17:01:19"}

Is blocked here ... 
But nice job :)

**Comment by 0x1Avram** [comment]
Hello,
If you can share the sample, I can look into it and try to fix it.

**Comment by tecnoweb** [comment]
> Hello,
> If you can share the sample, I can look into it and try to fix it.

can you provide mail I will send file no problem

**Comment by 0x1Avram** [comment]
Writing it as a string concatenation so I hopefully don't get overwhelmed with spam:
'0x1avram' + '@gmail.com'

**Comment by tecnoweb** [comment]
done send

**Comment by 0x1Avram** [comment]
Fixed issue.
The nice part is that the code actually worked. It's just that it was incredibly slow due to the size of the obfuscated file. It took a few hours to deobfuscate it. :D 
I found some way to do the deobfuscation faster, updated the project and created a new release.
Even with this update, for files that are quite large (a few megabytes) and heavily obfuscated, the deobfuscation might take a few minutes. Because of this, I also added more log messages showing that the deobfuscator is running and what progress is being made.
If you encounter other issues, please let me know.

**Comment by tecnoweb** [comment]
thanks sir :)
